# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: ZZOM
title: 캐릭터 일러스트 강좌 with 프로크리에이트
email: project.zzom@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  번역서 '캐릭터 일러스트 강좌 with 프로크리에이트' 도서 지원 페이지입니다.
# twitter_username: username
# github_username: username
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
breadcrumbs: false

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "번역하는 개발자"
  email: codelabor@gmail.com
  avatar : "/assets/images/profile/profile-bomber.jpg"
  bio    : "프로젝트 ZZOM 운영자"
#  instagram: "codelabor"
#  threads: "codelabor"
#  facebook: "sangjae.shin"
#  x: "codelabor"
#  youtube: "http://youtube.com/@translating-developer"
  links:
#    - label: "Website"
#      icon: "fas fa-fw fa-link"
#      url: "https://"
#    - label: "Twitter"
#      icon: "fab fa-fw fa-twitter-square"
#      url: "https://twitter.com/"
#    - label: "GitHub"
#      icon: "fab fa-fw fa-github"
#      url: "https://github.com/"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://instagram.com/"
     - label: "News Letter"
       icon: "fa-solid fa-link"
       url: "https://project-zzom.stibee.com/"       
     - label: "Littly"
       icon: "fa-solid fa-link"
       url: "https://litt.ly/codelabor"
       
# target="_blank" 되지 않음
footer:
 links:
  - label: "YouTube"
    icon: "fa-brands fa-youtube"
    url: "https://www.youtube.com/@zzom/" 
  - label: "TikTok"
    icon: "fa-brands fa-tiktok"
    url: "https://www.tiktok.com/@project.zzom"      
  - label: "X"
    icon: "fa-brands fa-x-twitter"
    url: "https://x.com/project_zzom/"
  - label: "Instagram"
    icon: "fa-brands fa-instagram"
    url: "https://www.instagram.com/project.zzom/"
  - label: "Thread"
    icon: "fa-brands fa-threads"
    url: "https://www.threads.net/@project.zzom"     
  - label: "Facebook"
    icon: "fa-brands fa-facebook"
    url: "https://www.facebook.com/project.zzom/"
  - label: "Bluesky"
    icon: "fa-brands fa-bluesky"
    url: "https://bsky.app/profile/project-zzom.bsky.social"          
  - label: "GitHub"
    icon: "fa-brands fa-github"
    url: "https://github.com/project-zzom"     

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


#### Custom ####  

# Google Analytics
google_analytics: 'G-FL5818NYCK'

# Google Adsense
adsense: "enabled"
adsense-data-ad-client: "ca-pub-5050141342916334"
#adsense-data-ad-slot-vertical: "9543862036"
#adsense-data-ad-slot-horizontal: "2009821092"
#adsense-data-ad-slot-square: "1542083085"
